item {
    id: 1
    name: 'player'
}

item {
    id: 2
    name: 'soccer ball'
}

item {
    id: 3
    name: 'soccer cleats'
}

item {
    id: 4
    name: 'trophy'
}

item {
    id: 5
    name: 'stadium'
}
